In [3]:
key = convert(UInt8, 30)
plain = [convert(UInt8, x) for x in [0,1,2,3,4,5,6,7,8,9]]

10-element Array{UInt8,1}:
 0x00
 0x01
 0x02
 0x03
 0x04
 0x05
 0x06
 0x07
 0x08
 0x09

In [4]:
function ECBC(plain, key)
    IV = convert(UInt8, 99)
    cypher = [convert(UInt8, x) for x in zeros(length(plain))]

    xor = IV
    for i in 1:length(plain)
        xor = (plain[i] ⊻ xor) ⊻ key
        cypher[i] = xor
    end
    return cypher
end

function DCBC(cypher, key)
    IV = convert(UInt8, 0)
    plain = [convert(UInt8, x) for x in zeros(length(cypher))]

    xor = IV
    for i in 1:length(plain)
        plain[i] = (cypher[i] ⊻ key) ⊻ xor
        xor = cypher[i]
    end
    return plain
end

DCBC (generic function with 1 method)

In [5]:
cypher = ECBC(plain, key)

10-element Array{UInt8,1}:
 0x7d
 0x62
 0x7e
 0x63
 0x79
 0x62
 0x7a
 0x63
 0x75
 0x62

In [6]:
decoded = DCBC(cypher, key)

10-element Array{UInt8,1}:
 0x63
 0x01
 0x02
 0x03
 0x04
 0x05
 0x06
 0x07
 0x08
 0x09

In [7]:
function ECRT(plain, key)
    cypher = [convert(UInt8, x) for x in zeros(length(plain))]

    crt = convert(UInt8, 0) + convert(UInt8, 33)
    for i in 1:length(plain)
        xor = crt ⊻ key
        cypher[i] = xor ⊻ plain[i]
        crt += convert(UInt8, 1)
    end
    return cypher
end

function DCRT(cypher, key)
    plain = [convert(UInt8, x) for x in zeros(length(cypher))]

    crt = convert(UInt8, 0) + convert(UInt8, 33)
    for i in 1:length(plain)
        xor = crt ⊻ key
        plain[i] = xor ⊻ cypher[i]
        crt += convert(UInt8, 1)
    end
    return plain
end

DCRT (generic function with 1 method)

In [8]:
cypher = ECRT(plain, key)

10-element Array{UInt8,1}:
 0x3f
 0x3d
 0x3f
 0x39
 0x3f
 0x3d
 0x3f
 0x31
 0x3f
 0x3d

In [9]:
decoded = DCRT(cypher, key)

10-element Array{UInt8,1}:
 0x00
 0x01
 0x02
 0x03
 0x04
 0x05
 0x06
 0x07
 0x08
 0x09